version: '2'

services:
  metabase:
    image: metabase/metabase
    ports:
      - 3333:3000
    volumes:
      - ./src/plugins/:/plugins

  de-sprint-6:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-sprint-6:v2024-01-25r2
    ports:
      - 3000:3000
      - 3002:3002
      - 15432:5432
    volumes:
      - mydb:/var/lib/postgresql
      - ./src/dags:/lessons/dags

volumes:
  mydb:

